### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by 91Abdullah** [Retinal-Research/NN-MOBILENET#2]
Hi,

I have read your paper but I could not find any documentation to perform inference. Can you tell me how can I test some images using your model?

Regards

**Comment by ChongQingNoSubway** [comment]
I provided the inference model in main.py (parser.add_argument('--eval', type=str2bool, default=False, help='Perform evaluation only'))

**Comment by 91Abdullah** [comment]
Thanks @ChongQingNoSubway for pointing this out. For testing images I need to use this argument, right?

--eval_data_path

**Comment by ChongQingNoSubway** [comment]
Yes, please carefully with data augmentation in your own testing set.
I updated the pre-trained weight for rexnet_3.0.pth, if you want to train on your dataset.

**Comment by 91Abdullah** [comment]
How to do data augmentation?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChongQingNoSubway** [comment]
All details in dataset.py.  
You just need to replace the --eval_data_path and --eval for inference if keep the same default setting with our code for both the training and validation sets.
