### ISSUE TITLE
About the "model" module

### ISSUE THREAD

**Issue by grasscarp7** [Retinal-Research/NN-MOBILENET#3]
`from model.resnext import ReXNetV1`

Hello, could you please clarify whether "model" is a folder or a package that needs to be installed? I am having trouble locating it. Thank you !

**Comment by ChongQingNoSubway** [comment]
Code has been updated. Thanks for the reminder

**Comment by grasscarp7** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
