### ISSUE TITLE
application

### ISSUE THREAD

**Issue by magic-fortune** [Retinal-Research/NN-MOBILENET#5]
Greetings! I noticed that the MICCAI 2023 Macular Degeneration Detection Challenge has already concluded, however, I am interested in conducting research in this area. May I kindly inquire about the possibility of obtaining the dataset used for this competition?

    Best regards！

**Comment by ChongQingNoSubway** [comment]
Thank you so much for expressing interest in our work. I believe the MMAC dataset has now published its training set, which you can download at the website provided below:
https://codalab.lisn.upsaclay.fr/competitions/12441

Unfortunately, without official authorization, I am unable to provide you with the dataset directly.

**Comment by magic-fortune** [comment]
Thank you so much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Retinal-Research/NN-MOBILENET"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 中午12:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Retinal-Research/NN-MOBILENET] application (Issue #5)





 
Thank you so much for expressing interest in our work. I believe the MMAC dataset has now published its training set, which you can download at the website provided below:
 https://codalab.lisn.upsaclay.fr/competitions/12441
 
Unfortunately, without official authorization, I am unable to provide you with the dataset directly.
